Vagrant.configure("2") do |config|
#  config.vm.box = "debian/bookworm64"

  config.vm.define :debian do |debian|
    debian.vm.box = "debian/bookworm64"
    debian.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 4
      domain.nested = true
    end
  end
end
