Vagrant.configure("2") do |config|
  config.vm.define :beta_vm do |beta_vm|
    beta_vm.vm.provider :libvirt do |v|
      v.memory = 4096
      v.cpus = 8
      v.video_type = 'virtio'
      v.video_accel3d = true
      v.graphics_gl = true
      v.graphics_type = 'spice'
      v.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
      v.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
      #v.graphics_autoport = 'no'
      v.cputopology :sockets => '1', :cores => '4', :threads => '2'
    end
    beta_vm.vm.box = "generic/ubuntu2310"
  end
end
