Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2310"

  # config.vm.define "apt-cacher.test"

  config.vm.provider :libvirt do |libvirt|
    # libvirt.default_prefix = ""
    libvirt.graphics_type = "spice"
    libvirt.video_type = 'qxl'
  end

  # Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
