Vagrant.configure("2") do |config|
#  config.vm.box = "generic/ubuntu2204"

  config.vm.define :ubuntults do |ubuntults|
    ubuntults.vm.box = "generic/ubuntu2204"
    ubuntults.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 4
      domain.nested = true
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "Mailcow.template/src/ansible/uni.yml"
    end
  end

  config.vm.define :ubuntulatest do |ubuntulatest|
    ubuntulatest.vm.box = "generic/ubuntu2204"
    ubuntulatest.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 4
      domain.nested = true
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "Mailcow.template/src/ansible/uni.yml"
    end
  end
end
