Vagrant.configure("2") do |config|
  config.vm.define :beta_vm do |beta_vm|
    beta_vm.vm.provider :libvirt do |v|
      v.memory = 2048
      v.cpus = 2
      v.video_type = 'virtio'
      v.video_accel3d = true
      v.graphics_gl = true
      v.graphics_type = 'spice'
      v.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
      v.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
      #v.graphics_autoport = 'no'
      v.cpuset = '14-15'
      v.cputopology :sockets => '1', :cores => '1', :threads => '2'
    end
    beta_vm.vm.box = "debian/bullseye64"
    beta_vm.vm.network "private_network", ip: "10.66.60.3"
    # beta_vm.vm.network "forwarded_port", guest: 80, host: 8881, protocol: "tcp"
  end
end
